### ISSUE TITLE
Homebrew maclaunch install error message on Big Sur (Intel)

### ISSUE THREAD

**Issue by andrewcrook** [hazcod/homebrew-hazcod#1]
Hello

I am getting the current message when trying to install maclaunch . 
CLT (Xcode Command-line tools) is on version 12.2 (12B45b) on my machine which is the current on macOS 11 Big Sur's release.

`==> Installing maclaunch from hazcod/hazcod
==> Downloading https://codeload.github.com/HazCod/maclaunch/zip/1.0
######################################################################## 100.0%
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.`

**Comment by hazcod** [comment]
HI @andrewcrook , this seems to be related to homebrew.
Can you issue ` sudo rm -rf /Library/Developer/CommandLineTools && sudo xcode-select --install`

**Comment by andrewcrook** [comment]
> HI @andrewcrook , this seems to be related to homebrew.
> Can you issue ` sudo rm -rf /Library/Developer/CommandLineTools && sudo xcode-select --install`

Many thanks this has worked. 
Although the version installed seems to be the same.
